function fluidicStageManualMode(instr)
%This function controls the popup menu for the fluidic stage settings
% shons 2013

handles.mainWindow = figure(...
    'Position', [360, 200, 400, 500],...
    'Menu', 'None',...
    'Name', 'Fluidic Stage Settings',...
    'WindowStyle', 'modal',...  %normal , modal, docked.
    'Visible', 'on',...
    'NumberTitle', 'off',...
    'CloseRequestFcn', {@closeWindow});

%set up main
handles.mainPanel = uipanel(...
    'parent',handles.mainWindow,...
    'Title','',...
    'Unit','Pixels',...
    'BackgroundColor',[0.9 0.9 0.9 ],...
    'Visible','on',...
    'Units', 'normalized', 'Position', [.005, .005, .990, .990]);

%Exit button
handles.exitButton = uicontrol(...
    'parent',handles.mainPanel,...
    'Style','pushbutton',...
    'Units', 'normalized', 'Position', [.7, .035, .225, .05],...
    'String','Exit',...
    'Callback',{@exit_Callback, handles});

%Description String
handles.stringTitle = uicontrol(...
    'parent',handles.mainPanel,...
    'Style','text',...
    'HorizontalAlignment','center',...
    'BackgroundColor',[0.9 0.9 0.9 ],...
    'FontWeight','bold',...
    'Units', 'normalized', 'Position', [.1, .9, .8, .05],...
    'String','Fluidic Stage Manual Mode');


%%
% motor position status -- GUI elements first and then callback functions
% 'Position', [.x-offset, .y-offset, .width, .height],...

% Description string - X motor position
handles.XmotorPostionString = uicontrol(...
    'parent',handles.mainPanel,...
    'Style','text',...
    'HorizontalAlignment','left',...
    'BackgroundColor',[0.9 0.9 0.9 ],...
    'Units', 'normalized', 'Position', [0.1, .8, .25, .05],...
    'String','X Stage Position = ');

handles.XmotorPositionValue = uicontrol(...
     'parent',handles.mainPanel,...
     'Style','text',...
     'HorizontalAlignment','left',...
     'BackgroundColor',[0.9 0.9 0.9 ],...
     'Units', 'normalized', 'Position', [.4, .8, .25, .05],...
     'String','-');

% Description string - Z motor position
handles.ZmotorPostionString = uicontrol(...
    'parent',handles.mainPanel,...
    'Style','text',...
    'HorizontalAlignment','left',...
    'BackgroundColor',[0.9 0.9 0.9 ],...
    'Units', 'normalized', 'Position', [0.1, .75, .25, .05],...
    'String','Z Stage Position = ');

handles.ZmotorPositionValue = uicontrol(...
     'parent',handles.mainPanel,...
     'Style','text',...
     'HorizontalAlignment','left',...
     'BackgroundColor',[0.9 0.9 0.9 ],...
     'Units', 'normalized', 'Position', [.4, .75, .25, .05],...
     'String','-');


%%
% stage movement -- GUI elements first and then callback functions

% GUI elements

% Description string - 'X Step Size' 
handles.XStepString = uicontrol(...
    'parent',handles.mainPanel,...
    'Style','text',...
    'BackgroundColor',[0.9 0.9 0.9 ],...
    'HorizontalAlignment','left',...
    'Units', 'normalized', 'Position', [.1, .67, .2, .05],...
    'String','X (mm)');

% X Step Size for fluidic stage
handles.XStepValue = uicontrol(...
    'parent',handles.mainPanel,...
    'Style','edit','Enable','on',...
    'Units', 'normalized', 'Position', [.4965, .67, .3215, .06],...
    'String','9.02',...  % default value = 9.02 mm b/t wells on 96 plate
    'Callback',{@XStepSize_Callback});

% X Left Button for fluidic stage movement
handles.XLeftButton = uicontrol(...
    'parent',handles.mainPanel,...
    'Style','pushbutton','Enable','on',...
    'Units', 'normalized', 'Position', [.3625, .67, .125, .06],...
    'String','<',...
    'Callback',{@XLeftButton_Callback});
    
% X Right Button for fluidic stage movement
handles.XRightButton = uicontrol(...
    'parent',handles.mainPanel,...
    'Style','pushbutton','Enable','on',...
    'Units', 'normalized', 'Position', [.825, .67, .125, .06],...
    'String','>',...
    'Callback',{@XRightButton_Callback});

% Description string - 'Z Step Size' 
handles.ZStepString = uicontrol(...
    'parent',handles.mainPanel,...
    'Style','text',...
    'BackgroundColor',[0.9 0.9 0.9 ],...
    'HorizontalAlignment','left',...
    'Units', 'normalized', 'Position', [.1, .6, .15, .05],...
    'String','Z (mm)');

% Z Step Size for fluidic
handles.ZStepValue = uicontrol(...
    'parent',handles.mainPanel,...
    'Style','edit','Enable','on',...
    'Units', 'normalized', 'Position', [.4965, .6, .3215, .06],...
    'String','1',...   % default value = 1 mm
    'Callback',{@ZStepSize_Callback});

% Z Left Button for Fluidic stage movement
handles.ZLeftButton = uicontrol(...
    'parent',handles.mainPanel,...
    'Style','pushbutton','Enable','on',...
    'Units', 'normalized', 'Position', [.3625, .6, .125, .06],...
    'String','^',...
    'Callback',{@ZLeftButton_Callback});

% Z Right Button for Fluidic stage movement
handles.ZRightButton = uicontrol(...
    'parent',handles.mainPanel,...
    'Style','pushbutton','Enable','on',...
    'Units', 'normalized', 'Position', [.825, .6, .125, .06],...
    'String','v',...
	'Callback',{@ZRightButton_Callback});


%%
% callback functions

% function to manually move fluidic stage in -X
function reply = XLeftButton_Callback(hObject,eventdata)
%    selected_val = get(hObject,'Value')
    distanceStr = get(handles.XStepValue,'String');
    distanceMm = str2num(distanceStr);
    % move motor
    instr.fluidicStage.move_x(distanceMm);
end

% function to manually move fluidic stage in +X
function reply = XRightButton_Callback(hObject,eventdata)
%    selected_val = get(hObject,'Value')
    distanceStr = get(handles.XStepValue,'String');
    distanceMm = str2num(distanceStr);
    % move motor
    instr.fluidicStage.move_x(distanceMm);
end

% function to manually move fluidic stage in -Z
function reply = ZLeftButton_Callback(hObject,eventdata)
%    selected_val = get(hObject,'Value')
    distanceStr = get(handles.ZStepValue,'String');
    distanceMm = str2num(distanceStr);
    % move motor
    instr.fluidicStage.move_z(distanceMm,'-');
end

% function to manually move fluidic stage in +Z
function reply = ZRightButton_Callback(hObject,eventdata)
%    selected_val = get(hObject,'Value')
    distanceStr = get(handles.ZStepValue,'String');
    distanceMm = str2num(distanceStr);
    % move motor
    instr.fluidicStage.move_z(distanceMm,'+');
end

%%
% Create timer to query the motor's position every 1 sec
handles.timer = timer('ExecutionMode', 'fixedRate','Period', 1,...
    'TimerFcn', {@queryPosition_Callback,handles});

% start timer
start(handles.timer);

% function to manually move fluidic stage in -X
function reply = queryPosition_Callback(hObject,eventdata,handles)
    instr.fluidicStage.get_x_position();
    set(handles.XmotorPositionValue,'String',num2str(instr.fluidicStage.XMotorPosition)); % update GUI element
    pause(0.1); % let the query finish
    instr.fluidicStage.get_z_position();
    set(handles.ZmotorPositionValue,'String',num2str(instr.fluidicStage.ZMotorPosition)); % update GUI element
end


function exit_Callback(hObject,eventdata,handles)
%     error_message = GetLaserSettings;
     error_message = '';
     if logical(length(error_message)) == 0
         close(handles.mainWindow);
     end
end

function closeWindow(hObject,eventdata)
        %display warning if coordiante system not properly set up; e.g.
        %when closing window instead of exit button
        %check if coordiante System is set up properly
%         error_message = GetLaserSettings;
        stop(handles.timer); 
        error_message = '';
         if logical(length(error_message)) == 0
             delete(gcbf);
         end
end

end

