function [rtn, val] = popup_dialog(msg,list)

   popup = dialog('WindowStyle', 'modal', ...
                          'Units', 'normalized', ...
                          'Position', [0 0 .26 .16], ...
                          'Name', 'New User');
    
    popup_text = uicontrol('Parent', popup, ...
                                  'Style', 'text', ...
                                  'Units', 'normalized', ...
                                  'Position', [.23 .60 .41 .19], ...
                                  'HorizontalAlignment', 'left', ...
                                  'FontSize', 11, ...
                                  'String', msg, ...
                                  'ForegroundColor', [0.33, 0.12, 0.54]);
                                  
if (isempty(list))                      
    popup_edit = uicontrol('Parent', popup, ...
                                  'Style', 'edit', ...
                                  'Units', 'normalized', ...
                                  'Position', [.23 .41 .41 .21], ...
                                  'BackgroundColor', [1 1 1], ...
                                  'FontSize', 10, ...
                                  'Callback', @popup_edit_cb);
else                              
    popup_list = uicontrol('Parent', popup, ...
                                  'Style', 'popupmenu', ...
                                  'String', list,...
                                  'Units', 'normalized', ...
                                  'Position', [.23 .41 .41 .21], ...
                                  'BackgroundColor', [1 1 1], ...
                                  'FontSize', 10, ...
                                  'Callback', @popup_list_cb);
end                              
    popup_done = uicontrol('Parent', popup, ...
                                  'Style', 'pushbutton', ...
                                  'Units', 'normalized', ...
                                  'Position', [.68 .21 .19 .19], ...
                                  'String', 'Save', ...
                                  'FontSize', 10, ...
                                  'Enable', 'off', ...
                                  'Callback', @popup_done_cb);
                              
    popup_cancel = uicontrol('Parent', popup, ...
                                  'Style', 'pushbutton', ...
                                  'Units', 'normalized', ...
                                  'Position', [.28 .21 .19 .19], ...
                                  'String', 'Cancel', ...
                                  'FontSize', 10, ...
                                  'Enable', 'on', ...
                                  'Callback', @popup_cancel_cb);
                              
    movegui(popup, 'center')
    
    uiwait;
                              
                              
% ------------------------- Callback Function ----------------------------

    function popup_edit_cb(hObject, eventdata)     
        strName = get(popup_edit, 'String');
        if (~isempty(strName))
            set(popup_done, 'Enable', 'on')
        end
    end

    function popup_list_cb(hObject, eventdata)
        listStr = get(popup_list, 'String');
        listVal = get(popup_list, 'Value');
        val = listStr(listVal);
        % enable done button
        set(popup_done, 'Enable', 'on');
    end

    function popup_done_cb(hObject, eventdata)
        rtn=1;
        uiresume;
        close(popup);
    end

    function popup_cancel_cb(hObject, eventdata)
        rtn=0;
        val = {};
        uiresume;
        close(popup);
    end

end