function h = busy_dlg(dialog_str)
    h = figure('NumberTitle', 'off', ...
               'MenuBar', 'none', ...
               'ToolBar', 'none', ...
               'Units', 'normalized', ...
               'Position', [0 0 0.09, 0.06]);
    movegui(h, 'center');
    uicontrol('Style','text', ...
              'String','BUSY...', ...
              'BackGroundColor', [0.8, 0.8, 0.8],...
              'FontSize', 12, ...
              'FontWeight', 'bold', ...
              'Units','normalized',...
              'Position',[0 0 1 1]);
    drawnow
end

