function gui_return = view_recipe(gui)
STAT_TXT_FONT = 11;

% ‘Select peaks’ should be a push-button that pops up a GUI window. It's callback should call a function with code like this...
% 
% x = [];
% y = [];
% plot(toPlot); % plot all peaks to figure out which to track
% title('zoom to peak group, press <enter>, and select FUNCTIONAL peak to track for ch1');
% pause; % pause allows user to zoom into group of peaks
% [xi,yi,button] = ginput(1);
% initXfunctionalPeaks(1) = round(xi);

gui.mainWindow = figure(...
    'Position', [360, 200, 400, 600],...
    'Menu', 'None',...
    'Name', 'Manual Coordinate Setup',...
    'WindowStyle', 'normal',...  %normal , modal, docked.
    'Visible', 'on',...
    'NumberTitle', 'off',...
    'CloseRequestFcn', {@closeWindow});

%set up main
gui.mainPanel = uipanel(...
    'parent', gui.mainWindow,...
    'Title','',...
    'Unit','Pixels',...
    'BackgroundColor',[0.9 0.9 0.9 ],...
    'Visible','on',...
    'Units', 'normalized', 'Position', [.005, .005, .990, .990]);

%Description String
gui.stringTitle = uicontrol(...
    'parent', gui.mainPanel,...
    'Style','text',...
    'HorizontalAlignment','center',...
    'BackgroundColor',[0.9 0.9 0.9 ],...
    'FontWeight','bold',...
    'Units', 'normalized', 'Position', [.1, .75, .8, .2],...
    'String','Recipe File');

%Recipe Table

recipe =  guidata(gui.mainPanel);

gui.recipe_table = uitable(...,
        'parent', gui.mainPanel,...
        'ColumnName', {'Well #','Time (min)', 'Velocity (uL/min)', 'Reagent', 'Comment'},...
        'ColumnFormat', {'char', 'char', 'char', 'char', 'char'},...
        'ColumnEditable', [false, false, false, false, false],...
        'Units','normalized',...
        'Position', [.1, .1, .8, .8],...
        'Data', recipe,...
        'FontSize', 9,...
        'ColumnWidth',{50,50,50,50,50},...
        'CellEditCallback',{@cell_edit_cb},...
        'CellSelectionCallback', {@cell_sel_cb},...
        'Enable','on');

%OK button
gui.ok_button = uicontrol(...
    'parent', gui.mainPanel,...
    'Style', 'pushbutton',...
    'units', 'normalized',...
    'position', [.7,.1,.18,.1],...
    'string', 'OK',...
    'callback', @ok_button_cb);

%Cancel button
gui.cancel_button = uicontrol(...
    'parent', gui.mainPanel,...
    'Style', 'pushbutton',...
    'units', 'normalized',...
    'position', [.5,.1,.18,.1],...
    'string', 'Cancel',...
    'callback', @cancel_button_cb);


function exit_Callback(hObject,eventdata)
         close(gui.mainWindow);    
end

function closeWindow(hObject,eventdata)   
         delete(gcbf);
end



%     function cancel_button_cb(hObject, eventdata)
%         @exit_Callback(hObject, eventdata)
%     end

gui_return = gui;

end