% obj is the main testbench object
% --- build up a camera control ui in the assigned panel (or popup)
% parentName is a string describing of the parent panel (or popup)
% --- 1. For popup: should be like 'manual', 'selectPeaks' ...
% --- 2. For panel: should be the same as in panel_index function
% parentObj is the parent object for the ui (type: double)
% Victor Bass 2013;
% Modified by Vince Wu - Nov 2013

function obj = camera_ui(obj, parentName, parentObj, position)

parentStruct = getParentStruct(parentName);
if (~isempty(strfind(parentStruct, 'panel')))
    panelIndex = str2double(parentStruct(end - 1));
    parentStruct = parentStruct(1:end - 3);
else
    panelIndex = 1;
end

obj.gui.(parentStruct)(panelIndex).cameraUI.mainPanel = uipanel(...
    'parent', parentObj,...
    'Unit','Pixels',...
    'BackgroundColor', [0.9, 0.9, 0.9 ],...
    'Visible','on',...
    'units','normalized',...
    'Title','Microscope Camera:',...
    'FontSize', 9,...
    'FontWeight', 'bold',...
    'Position', position);

% Initiate axes for microscopr camera
obj.gui.(parentStruct)(panelIndex).cameraUI.cameraPreviewAxe = axes(...
    'Parent', obj.gui.(parentStruct)(panelIndex).cameraUI.mainPanel,...
    'Units', 'normalized', ...
    'Position', [.0, .0, .99, .99], ...
    'Color', [.85 .85 .85], ...
    'YDir', 'reverse', ...
    'NextPlot', 'add', ...
    'box', 'on');
axis on;

if (~isempty(obj.instr.camera))
    cam_enable = 'on';
else
    cam_enable = 'off';
end

obj.gui.(parentStruct)(panelIndex).cameraUI.loadCameraButton = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).cameraUI.mainPanel,...
    'Style', 'pushbutton', ...
    'Enable', cam_enable, ...
    'Units', 'normalized', ...
    'Position', [.5, .02, .12, .06], ...
    'String', 'Load', ...
    'FontSize', 9, ...
    'Callback', {@load_camera_cb, obj, parentStruct, panelIndex});

obj.gui.(parentStruct)(panelIndex).cameraUI.captureCameraButton = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).cameraUI.mainPanel, ...
    'Style', 'pushbutton', ...
    'Enable', cam_enable, ...
    'Units', 'normalized', ...
    'Position', [.65, .02, .12, .06], ...
    'String', 'Capture', ...
    'FontSize', 9, ...
    'Callback', {@capture_camera_cb, obj});

obj.gui.(parentStruct)(panelIndex).cameraUI.closeCameraButton = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).cameraUI.mainPanel,...
    'Style', 'pushbutton', ...
    'Enable', cam_enable, ...
    'Units', 'normalized', ...
    'Position', [.8, .02, .12, .06], ...
    'String', 'Close', ...
    'FontSize', 9, ...
    'Callback', {@close_camera_cb, obj, parentStruct, panelIndex});

end

%% MICROSCOPE CAMERA CALLBACKS
function load_camera_cb(~, ~, obj, parentStruct, panelIndex)
obj.instr.camera.PreviewAxes = obj.gui.(parentStruct)(panelIndex).cameraUI.cameraPreviewAxe;
obj.instr.camera.start();
end

function capture_camera_cb(~, ~, obj)
obj.instr.camera.capture();
end

function close_camera_cb(~, ~, obj, parentStruct, panelIndex)
obj.instr.camera.PreviewAxes = obj.gui.(parentStruct)(panelIndex).cameraUI.cameraPreviewAxe;
obj.instr.camera.close();
end