% obj is the main testbench object
% --- build up a detector control ui in the assigned panel (or popup)
% parentName is a string describing of the parent panel (or popup)
% --- 1. For popup: should be like 'manual', 'selectPeaks' ...
% --- 2. For panel: should be the same as in panel_index function
% parentObj is the parent object for the ui (type: double)
% Victor Bass 2013;
% Modified by Vince Wu - Nov 2013

function obj = detector_ui(obj, parentName, parentObj, position)

parentStruct = getParentStruct(parentName);
if (~isempty(strfind(parentStruct, 'panel')))
    panelIndex = str2double(parentStruct(end - 1));
    parentStruct = parentStruct(1:end - 3);
else
    panelIndex = 1;
end

% panel element size variables
stringBoxSize = [0.21, 0.12];
pushButtonSize = [0.275, 0.15];

% detector panel
obj.gui.(parentStruct)(panelIndex).detectorUI.mainPanel = uipanel(...
    'Parent', parentObj, ...
    'BackgroundColor', [0.9, 0.9 0.9], ...
    'Visible','on', ...
    'Units','normalized', ...
    'Title','Detector', ...
    'FontSize', 9, ...
    'FontWeight','bold', ...
    'Position', position);

% auto update string
obj.gui.(parentStruct)(panelIndex).detectorUI.detectorUpdateString = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).detectorUI.mainPanel, ...
    'Style', 'text', ...
    'BackgroundColor', [0.9, 0.9, 0.9], ...
    'Units', 'normalized', ...
    'String', 'Auto-update', ...
    'HorizontalAlignment', 'left', ...
    'FontSize', 9, ...
    'Position', [.025, .84, stringBoxSize]);

% auto update checkbox
obj.gui.(parentStruct)(panelIndex).detectorUI.detectorUpdateCheckbox = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).detectorUI.mainPanel, ...
    'Style', 'checkbox', ...
    'BackgroundColor', [0.9, 0.9, 0.9], ...
    'Enable', 'on', ...
    'Units', 'normalized', ...
    'Position', [0.196, 0.84, 0.06, 0.12], ...
    'Callback', {@detector_auto_update_cb, obj, parentStruct, panelIndex});

% settings button
obj.gui.(parentStruct)(panelIndex).detectorUI.detectorSettingButton = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).detectorUI.mainPanel, ...
    'Style', 'pushbutton', ...
    'Enable', 'on', ...
    'Units', 'normalized', ...
    'Position', [.7, .85, pushButtonSize], ...
    'String', 'Settings', ...
    'Callback', {@detector_settings_cb, obj});

% detector string
obj.gui.(parentStruct)(panelIndex).detectorUI.detectorString = uicontrol(...
    'parent', obj.gui.(parentStruct)(panelIndex).detectorUI.mainPanel, ...
    'Style','text', ...
    'BackgroundColor',[0.9 0.9 0.9 ], ...
    'HorizontalAlignment','left', ...
    'Units', 'normalized', ...
    'Position', [.025, .675, stringBoxSize], ...
    'String', 'Detector', ...
    'FontSize', 9);

% slot string
obj.gui.(parentStruct)(panelIndex).detectorUI.slotString = uicontrol(...
    'parent', obj.gui.(parentStruct)(panelIndex).detectorUI.mainPanel, ...
    'Style','text', ...
    'BackgroundColor',[0.9 0.9 0.9 ], ...
    'HorizontalAlignment','left', ...
    'Units', 'normalized', ...
    'Position', [.21, .675, stringBoxSize], ...
    'String', 'Slot', ...
    'FontSize', 9);

% channel string
obj.gui.(parentStruct)(panelIndex).detectorUI.channelString = uicontrol(...
    'parent', obj.gui.(parentStruct)(panelIndex).detectorUI.mainPanel, ...
    'Style','text', ...
    'BackgroundColor',[0.9 0.9 0.9 ], ...
    'HorizontalAlignment','left', ...
    'Units', 'normalized', ...
    'Position', [.34, .675, stringBoxSize], ...
    'String', 'Channel', ...
    'FontSize', 9);

% power string
try
    if obj.instr.laser.getParam('PowerUnit') == 0
        unit_str = 'dB';
    elseif obj.instr.laser.getParam('PowerUnit') == 1
        unit_str = 'W';
    end
catch ME
    msg = [obj.instr.laser.Name, ': Could not set laser power unit!'];
    obj.msg(msg);
    disp(ME.Message);
    unit_str = '??';
end

obj.gui.(parentStruct)(panelIndex).detectorUI.powerUnit = uicontrol(...
    'parent', obj.gui.(parentStruct)(panelIndex).detectorUI.mainPanel, ...
    'Style','text', ...
    'BackgroundColor',[0.9 0.9 0.9 ], ...
    'HorizontalAlignment','left', ...
    'Units', 'normalized', ...
    'Position', [.514, .675, stringBoxSize], ...
    'String', ['Power ','(',unit_str,')'], ...
    'FontSize', 9);

% include detector string
obj.gui.(parentStruct)(panelIndex).detectorUI.includeDetectorString = uicontrol(...
    'parent', obj.gui.(parentStruct)(panelIndex).detectorUI.mainPanel, ...
    'Style','text', ...
    'BackgroundColor',[0.9 0.9 0.9 ], ...
    'HorizontalAlignment','left', ...
    'Units', 'normalized', ...
    'Position', [.746, .675, stringBoxSize], ...
    'String', 'Include:', ...
    'FontSize', 9);


% for loop to draw ui's for each detector
numOfDetectors = obj.instr.detector.getProp('NumOfDetectors');
detectorBoxSize = [.1, min(.45/numOfDetectors, 0.16)];
selectedDetectors = obj.instr.detector.getProp('SelectedDetectors');
for i = 1:numOfDetectors
    [slot, channel] = obj.instr.detector.switchDetector(i);
    % loop position offset variable
    yVal = 0.49 - (i-1)*(detectorBoxSize(2) + 0.02);
    % detector number string
    obj.gui.(parentStruct)(panelIndex).detectorUI.detectorNums(i) = uicontrol(...
        'Parent', obj.gui.(parentStruct)(panelIndex).detectorUI.mainPanel, ...
        'Style', 'text', ...
        'BackgroundColor', [0.9, 0.9 0.9], ...
        'Units', 'normalized', ...
        'String', i, ...
        'FontSize', 8, ...
        'Position', [.0354, yVal, detectorBoxSize]);
    
    % detector slot number
    obj.gui.(parentStruct)(panelIndex).detectorUI.slotNums(i) = uicontrol(...
        'Parent', obj.gui.(parentStruct)(panelIndex).detectorUI.mainPanel, ...
        'Style', 'text', ...
        'BackgroundColor', [0.9, 0.9 0.9], ...
        'Units', 'normalized', ...
        'String', slot, ...
        'FontSize', 8, ...
        'Position', [.19, yVal, detectorBoxSize]);
    
    % detector channel number
    obj.gui.(parentStruct)(panelIndex).detectorUI.channelNum(i) = uicontrol(...
        'Parent', obj.gui.(parentStruct)(panelIndex).detectorUI.mainPanel, ...
        'Style', 'text', ...
        'BackgroundColor', [0.9, 0.9 0.9], ...
        'Units', 'normalized', ...
        'String', channel, ...
        'FontSize', 8, ...
        'Position', [.346, yVal, detectorBoxSize]);
    
    % detector power value
    power = obj.instr.detector.readPower(i);
    powerStr = sprintf('%0.1f', power);
    obj.gui.(parentStruct)(panelIndex).detectorUI.detectorPower(i) = uicontrol(...
        'Parent', obj.gui.(parentStruct)(panelIndex).detectorUI.mainPanel, ...
        'Style', 'text', ...
        'BackgroundColor', [0.9, 0.9 0.9], ...
        'Units', 'normalized', ...
        'String', powerStr, ...
        'FontSize', 8, ...
        'Position', [.49, yVal, .2, detectorBoxSize(2)]);
    
    % include detector
    % enable by default (Value = true)
    obj.gui.(parentStruct)(panelIndex).detectorUI.includeDetector(i) = uicontrol(...
        'Parent', obj.gui.(parentStruct)(panelIndex).detectorUI.mainPanel, ...
        'Style', 'checkbox', ...
        'BackgroundColor', [0.9, 0.9, 0.9], ...
        'Enable', 'on', ...
        'Value', selectedDetectors(i),...
        'Units', 'normalized', ...
        'Position', [0.784, yVal + 0.03 , 0.06, 0.12], ...
        'Callback', {@include_detector_checkbox_cb, obj, i});
end

end

%% Callback Functions
function detector_settings_cb(~, ~, obj)
obj.instr.detector.settingsWin;
end

function detector_auto_update_cb(hObject, ~, obj, parentStruct, panelIndex)
isChecked = get(hObject, 'Value');
if isChecked
    obj.timer.detectorReadTimer = timer(...
        'Name', 'Detector-Update-Timer', ...
        'ExecutionMode', 'fixedRate', ...
        'BusyMode', 'drop', ...
        'Period', obj.instr.detector.Param.UpdatePeriod, ...
        'TimerFcn', {@updatePowerValues, obj, parentStruct, panelIndex});
    start(obj.timer.detectorReadTimer);
else
    stop(obj.timer.detectorReadTimer);
    delete(obj.timer.detectorReadTimer);
end
end

function updatePowerValues(~, ~, obj, parentStruct, panelIndex)
PowerValues = obj.instr.detector.readPowerAll(); % Should be in dBW
numOfDetectors = obj.instr.detector.getProp('NumOfDetectors');
for j = 1:numOfDetectors
    powerStr = sprintf('%0.1f', PowerValues(j));
    set(obj.gui.(parentStruct)(panelIndex).detectorUI.detectorPower(j), 'String', powerStr);
end
end
% include detector callback
% if box is unchecked, deselect detector in class
function include_detector_checkbox_cb(hObject, ~, obj, index)
selected = get(hObject, 'Value');
selectedDetectors = obj.instr.detector.getProp('SelectedDetectors');
selectedDetectors(index) = selected;
obj.instr.detector.setProp('SelectedDetectors', selectedDetectors);
end

