% obj is the main testbench object
% --- build up a fluidic stage control ui in the assigned panel (or popup)
% parentName is a string describing of the parent panel (or popup)
% --- 1. For popup: should be like 'manual', 'selectPeaks' ...
% --- 2. For panel: should be the same as in panel_index function
% parentObj is the parent object for the ui (type: double)
% Victor Bass 2013;
% Modified by Vince Wu - Nov 2013

function obj = fluidic_tray_ui(obj, parentName, parentObj, position)

parentStruct = getParentStruct(parentName);
if (~isempty(strfind(parentStruct, 'panel')))
    panelIndex = str2double(parentStruct(end - 1));
    parentStruct = parentStruct(1:end - 3);
else
    panelIndex = 1;
end

% panel element size variables
stringBoxSize = [0.2, 0.15];
pushButtonSize = [0.175, 0.2];
popupSize = [0.1, 0.1];

% fluidic stage parent panel
obj.gui.(parentStruct)(panelIndex).fldTrayUI.mainPanel = uipanel(...
    'Parent', parentObj, ...
    'Unit','Pixels', ...
    'BackgroundColor', [0.9, 0.9 0.9], ...
    'Visible','on', ...
    'Units','normalized', ...
    'Title','Fluidic Tray', ...
    'FontSize', 9, ...
    'FontWeight','bold', ...
    'Position', position);

% eject tray button
obj.gui.(parentStruct)(panelIndex).fldTrayUI.ejectButton = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).fldTrayUI.mainPanel, ...
    'Style', 'pushbutton', ...
    'Enable', 'on', ...
    'Units', 'normalized', ...
    'Position', [.05, .75, pushButtonSize], ...
    'String', 'Eject', ...
    'Callback', {@fld_tray_ejectn_cb, obj, parentStruct, panelIndex});

% load tray button
obj.gui.(parentStruct)(panelIndex).fldTrayUI.loadButton = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).fldTrayUI.mainPanel, ...
    'Style', 'pushbutton', ...
    'Enable', 'off', ...
    'Units', 'normalized', ...
    'Position', [.25, .75, pushButtonSize], ...
    'String', 'Load', ...
    'Callback', {@fld_tray_load_cb, obj, parentStruct, panelIndex});

% settings button
obj.gui.(parentStruct)(panelIndex).fldTrayUI.settingsButton = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).fldTrayUI.mainPanel, ...
    'Style', 'pushbutton', ...
    'Enable', 'on', ...
    'Units', 'normalized', ...
    'Position', [.45, .75, pushButtonSize], ...
    'String', 'Settings', ...
    'Callback', {@fld_tray_settings_cb, obj});

% Front plate string
obj.gui.(parentStruct)(panelIndex).fldTrayUI.frontPlateString = uicontrol(...
    'parent', obj.gui.(parentStruct)(panelIndex).fldTrayUI.mainPanel, ...
    'Style','text', ...
    'BackgroundColor',[0.9 0.9 0.9 ], ...
    'HorizontalAlignment','left', ...
    'Units', 'normalized', ...
    'Position', [.65, .775, stringBoxSize], ...
    'String','FrontPlate', ...
    'FontSize', 8);

defaultFrontPlate = ...
    find(obj.AppSettings.FluidicStageParams.FrontPlateConfig == obj.instr.fluidicStage.PlateList);
if isempty(defaultFrontPlate)
    defaultFrontPlate = 1;
end
% Front plate popup menu
obj.gui.(parentStruct)(panelIndex).fldTrayUI.frontPlatePopup = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).fldTrayUI.mainPanel, ...
    'Style', 'popupmenu', ...
    'Enable', 'on', ...
    'Units', 'normalized', ...
    'Position', [.85, .85, popupSize], ...
    'String', num2str(obj.instr.fluidicStage.PlateList), ...
    'Value', defaultFrontPlate, ...
    'FontSize', 7, ...
    'Callback', {@front_plate_cb, obj, parentStruct, panelIndex});

% well string
obj.gui.(parentStruct)(panelIndex).fldTrayUI.wellString = uicontrol(...
    'parent', obj.gui.(parentStruct)(panelIndex).fldTrayUI.mainPanel, ...
    'Style','text', ...
    'BackgroundColor',[0.9 0.9 0.9 ], ...
    'HorizontalAlignment','left', ...
    'Units', 'normalized', ...
    'Position', [.1, .225, stringBoxSize], ...
    'String','Well #', ...
    'FontSize', 8);

% Back plate string
obj.gui.(parentStruct)(panelIndex).fldTrayUI.backPlateString = uicontrol(...
    'parent', obj.gui.(parentStruct)(panelIndex).fldTrayUI.mainPanel, ...
    'Style','text', ...
    'BackgroundColor',[0.9 0.9 0.9 ], ...
    'HorizontalAlignment','left', ...
    'Units', 'normalized', ...
    'Position', [.65, .2, stringBoxSize], ...
    'String','BackPlate', ...
    'FontSize', 8);

defaultBackPlate = ...
    find(obj.AppSettings.FluidicStageParams.BackPlateConfig == obj.instr.fluidicStage.PlateList);
if isempty(defaultBackPlate)
    defaultBackPlate = 1;
end
% Back plate popup menu
obj.gui.(parentStruct)(panelIndex).fldTrayUI.backPlatePopup = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).fldTrayUI.mainPanel, ...
    'Style', 'popupmenu', ...
    'Enable', 'on', ...
    'Units', 'normalized', ...
    'Position', [.85, .3, popupSize], ...
    'String', num2str(obj.instr.fluidicStage.PlateList), ...
    'Value', defaultBackPlate, ...
    'FontSize', 7, ...
    'Callback', {@back_plate_cb, obj, parentStruct, panelIndex});

totalWellNum = obj.AppSettings.FluidicStageParams.FrontPlateConfig + ...
    obj.AppSettings.FluidicStageParams.FrontPlateConfig;
% well popup menu
obj.gui.(parentStruct)(panelIndex).fldTrayUI.wellNumPopup = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).fldTrayUI.mainPanel, ...
    'Style', 'popupmenu', ...
    'Enable', 'on', ...
    'Units', 'normalized', ...
    'Position', [.25, .3, popupSize], ...
    'String', num2str((1:totalWellNum)'), ...
    'FontSize', 7);

% move button
obj.gui.(parentStruct)(panelIndex).fldTrayUI.moveButton = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).fldTrayUI.mainPanel, ...
    'Style', 'pushbutton', ...
    'Enable', 'off', ...
    'Units', 'normalized', ...
    'Position', [.45, .2, pushButtonSize], ...
    'String', 'Move', ...
    'Callback', {@fld_tray_move_cb, obj, parentStruct, panelIndex});

end

%% Callback Functions
function fld_tray_ejectn_cb(~, ~, obj, parentStruct, panelIndex)
obj.instr.fluidicStage.ejectTray;
if (obj.instr.fluidicStage.TrayEjected)
    msg = strcat(obj.instr.fluidicStage.Name, ' tray ejected');
    obj.msg(msg);
    set(obj.gui.(parentStruct)(panelIndex).fldTrayUI.ejectButton, 'Enable', 'off');
    set(obj.gui.(parentStruct)(panelIndex).fldTrayUI.loadButton, 'Enable', 'on');
end
end

function fld_tray_load_cb(~, ~, obj, parentStruct, panelIndex)
set(obj.gui.(parentStruct)(panelIndex).fldTrayUI.loadButton, 'Enable', 'off');
obj.instr.fluidicStage.loadTray;
if(obj.instr.fluidicStage.TrayLoaded)
    msg = strcat(obj.instr.fluidicStage.Name, ' tray loaded');
    obj.msg(msg);
    set(obj.gui.(parentStruct)(panelIndex).fldTrayUI.moveButton, 'Enable', 'on');
    set(obj.gui.(parentStruct)(panelIndex).fldTrayUI.ejectButton, 'Enable', 'on');
end
end

function fld_tray_settings_cb(~, ~, obj)
obj.instr.fluidicStage.settingsWin;
end

function front_plate_cb(hObject, ~, obj, parentStruct, panelIndex)
plateNumm = obj.instr.fluidicStage.PlateList(get(hObject, 'Value'));
obj.instr.fluidicStage.FrontPlateType = plateNumm;
obj.AppSettings.FluidicStageParams.FrontPlateConfig = plateNumm;
well_plate_list(obj, parentStruct, panelIndex);
end

function back_plate_cb(hObject, ~, obj, parentStruct, panelIndex)
plateNumm = obj.instr.fluidicStage.PlateList(get(hObject, 'Value'));
obj.instr.fluidicStage.BackPlateType = plateNumm;
obj.AppSettings.FluidicStageParams.BackPlateConfig = plateNumm;
well_plate_list(obj, parentStruct, panelIndex);
end

function fld_tray_move_cb(~, ~, obj, parentStruct, panelIndex)
% check to see if pump is running, then stop
if obj.instr.pump.Busy % is on
    obj.instr.pump.stop(); % stop pump
end
new_well = get(obj.gui.(parentStruct)(panelIndex).fldTrayUI.wellNumPopup, 'Value'); % get new well num
obj.instr.fluidicStage.move_to_well(new_well); % move to well
msg = [obj.instr.fluidicStage.Name, ': Current Well: ', obj.instr.fluidicStage.CurrentWell];
obj.msg(msg);
end

function well_plate_list(obj, parentStruct, panelIndex)
totalWellNum = ...
    obj.instr.fluidicStage.FrontPlateType + obj.instr.fluidicStage.BackPlateType;
set(obj.gui.(parentStruct)(panelIndex).fldTrayUI.wellNumPopup, ...
    'String', num2str((1:totalWellNum)'));
end