% obj is the main testbench object
% --- build up a multimeter control ui in the assigned panel (or popup)
% parentName is a string describing of the parent panel (or popup)
% --- 1. For popup: should be like 'manual', 'selectPeaks' ...
% --- 2. For panel: should be the same as in panel_index function
% parentObj is the parent object for the ui (type: double)
% Victor Bass 2013;
% Modified by Vince Wu - Nov 2013
% Modified by Pavel Kulik - Nov 2013

function obj = multimeter_ui(obj, parentName, parentObj, position)

parentStruct = getParentStruct(parentName);
if (~isempty(strfind(parentStruct, 'panel')))
    panelIndex = str2double(parentStruct(end - 1));
    parentStruct = parentStruct(1:end - 3);
else
    panelIndex = 1;
end

% panel element size variables
pushButtonSize = [0.4, 0.15];
editBoxSize = [0.4, 0.15];

% multimeter panel
obj.gui.(parentStruct)(panelIndex).multimeterUI.mainPanel = uipanel(...
    'Parent', parentObj, ...
    'Unit','Pixels', ...
    'BackgroundColor', [0.9, 0.9 0.9], ...
    'Visible','on', ...
    'Units','normalized', ...
    'Title','Multimeter', ...
    'FontSize', 9, ...
    'FontWeight','bold', ...
    'Position', position);

x_start = 0.5;
y_start = 0.7;

% measure voltage button
obj.gui.(parentStruct)(panelIndex).multimeterUI.voltButton = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).multimeterUI.mainPanel, ...
    'Style', 'pushbutton', ...
    'Enable', 'On', ...
    'Units', 'normalized', ...
    'Position', [x_start, y_start, pushButtonSize], ...
    'String','Measure Voltage', ...
    'Callback', {@volt_button_cb, obj});

x_align = x_start + 0.5;

% measure current button
obj.gui.(parentStruct)(panelIndex).multimeterUI.currentButton = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).multimeterUI.mainPanel, ...
    'Style', 'pushbutton', ...
    'Enable', 'On', ...
    'Units', 'normalized', ...
    'Position', [x_align, y_align, pushButtonSize], ...
    'String','Measure Current', ...
    'Callback', {@current_button_cb, obj});

x_align = x_start;
y_align = y_start - 0.4;

% save file name input
obj.gui.(parentStruct)(panelIndex).multimeterUI.file_input_box = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).multimeterUI.mainPanel, ...
    'Style', 'edit', ...
    'Enable', 'on', ...
    'Units', 'normalized', ...
    'Position', [x_align, y_align, editBoxSize]);

x_align = x_align + 0.5;

% save data button
obj.gui.(parentStruct)(panelIndex).multimeterUI.saveButton = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).multimeterUI.mainPanel, ...
    'Style', 'pushbutton', ...
    'Enable', 'On', ...
    'Units', 'normalized', ...
    'Position', [x_align, y_align, pushButtonSize], ...
    'String','Save Data', ...
    'Callback', {@save_button_cb, obj, parentStruct, panelIndex});

end

%% Callback Functions
function volt_button_cb(~, ~, obj)
obj.instr.multimeter.measure_DC_voltage;
end

function current_button_cb(~, ~, obj)
obj.instr.multimeter.measure_DC_current;
end

function save_button_cb(~, ~, obj, parentStruct, panelIndex)
file_name = get(obj.gui.(parentStruct)(panelIndex).multimeterUI.file_input_box, 'String');
obj.instr.multimeter.read_data(file_name);
end
