% obj is the main testbench object
% --- build up a power supply control ui in the assigned panel (or popup)
% parentName is a string describing of the parent panel (or popup)
% --- 1. For popup: should be like 'manual', 'selectPeaks' ...
% --- 2. For panel: should be the same as in panel_index function
% parentObj is the parent object for the ui (type: double)
% Victor Bass 2013;
% Modified by Vince Wu - Nov 2013
% Modified by Pavel Kulik - Nov 2013

function obj = power_supply_ui(obj, parentName, parentObj, position)

parentStruct = getParentStruct(parentName);
if (~isempty(strfind(parentStruct, 'panel')))
    panelIndex = str2double(parentStruct(end - 1));
    parentStruct = parentStruct(1:end - 3);
else
    panelIndex = 1;
end

% panel element size variables
stringBoxSize = [0.3, 0.15];
pushButtonSize = [0.275, 0.15];
editBoxSize = [0.25, 0.15];

% power supply panel
obj.gui.(parentStruct)(panelIndex).powerSupplyUI.mainPanel = uipanel(...
    'Parent', parentObj, ...
    'Unit','Pixels', ...
    'BackgroundColor', [0.9, 0.9 0.9], ...
    'Visible','on', ...
    'Units','normalized', ...
    'Title','Power Supply', ...
    'FontSize', 9, ...
    'FontWeight','bold', ...
    'Position', position);

x_start = 0.2;
y_start = 0.7;

% on button
obj.gui.(parentStruct)(panelIndex).powerSupplyUI.ONButton = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).powerSupplyUI.mainPanel, ...
    'Style', 'pushbutton', ...
    'Enable', 'On', ...
    'Units', 'normalized', ...
    'Position', [x_start, y_start, pushButtonSize], ...
    'String','On', ...
    'Callback', {@on_button_cb, obj});

x_align = x_start + 0.4;
y_align = y_start;

% off button
obj.gui.(parentStruct)(panelIndex).powerSupplyUI.offButton = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).powerSupplyUI.mainPanel, ...
    'Style', 'pushbutton', ...
    'Enable', 'Off', ...
    'Units', 'normalized', ...
    'Position', [x_align, y_align, pushButtonSize], ...
    'String','Off', ...
    'Callback', {@off_button_cb, obj});

x_align = x_start;
y_align = y_start - 0.5*y_start;

% voltage string
obj.gui.(parentStruct)(panelIndex).powerSupplyUI.voltString = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).powerSupplyUI.mainPanel, ...
    'Style','text', ...
    'BackgroundColor',[0.9 0.9 0.9 ], ...
    'HorizontalAlignment','left', ...
    'Units', 'normalized', ...
    'Position', [x_align, y_align, stringBoxSize], ...
    'String','Voltage(V) = ', ...
    'FontSize', 8);

x_align = x_align + 0.3;

% voltage display box
obj.gui.(parentStruct)(panelIndex).powerSupplyUI.voltDisplay = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).powerSupplyUI.mainPanel, ...
    'Style','edit', ...
    'Enable', 'on', ...
    'Units', 'normalized', ...
    'Position', [x_align, y_align, editBoxSize], ...
    'String', obj.instr.power_supply.getParam(Voltage), ...
    'Callback', {@voltage_display_cb, obj, parentStruct, panelIndex});

x_align = x_align + 0.3;

% settings button
obj.gui.(parentStruct)(panelIndex).powerSupplyUI.settingsButton = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).powerSupplyUI.mainPanel, ...
    'Style','pushbutton', ...
    'Enable', 'on', ...
    'Units', 'normalized', ...
    'Position', [x_align, y_align, pushButtonSize], ...
    'String','Settings', ...
    'Callback', {@settings_cb, obj});

x_align = x_start;
y_align = y_align - 0.3;

% current string
obj.gui.(parentStruct)(panelIndex).powerSupplyUI.currentString = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).powerSupplyUI.mainPanel, ...
    'Style','text', ...
    'BackgroundColor',[0.9 0.9 0.9 ], ...
    'HorizontalAlignment','left', ...
    'Units', 'normalized', ...
    'Position', [x_align, y_align, stringBoxSize], ...
    'String','Current(A) = ', ...
    'FontSize', 8);

x_align = x_align + 0.3;

% current display box
obj.gui.(parentStruct)(panelIndex).powerSupplyUI.currentDisplay = uicontrol(...
    'Parent', obj.gui.(parentStruct)(panelIndex).powerSupplyUI.mainPanel, ...
    'Style','edit', ...
    'Enable', 'on', ...
    'Units', 'normalized', ...
    'Position', [x_align, y_align, editBoxSize], ...
    'String', obj.instr.power_supply.getParam(Current), ...
    'Callback', {@current_display_cb, obj, parentStruct, panelIndex});

end

%% Callback Functions
function on_button_cb(~, ~, obj)
obj.instr.powerSupply.on;
end

function off_button_cb(~, ~, obj)
obj.instr.powerSupply.off;
end

function voltage_display_cb(~, ~, obj, parentStruct, panelIndex)
set(obj.gui.(parentStruct)(panelIndex).powerSupplyUI.voltDisplay, 'String', ...
    obj.instr.powerSupply.getParam(Voltage));
end

function settings_cb(~, ~, obj)
obj.instr.powerSupply.settingsWin;
end

function current_display_cb(~, ~, obj, parentStruct, panelIndex)
set(obj.gui.(parentStruct)(panelIndex).powerSupplyUI.currentDisplay, 'String', ...
    obj.instr.powerSupply.getParam(Current));
end